### ISSUE TITLE
0007-better-dashboard-management.patch Guild Loading Issue

### ISSUE THREAD

**Issue by ghost** [zeppelinhangar/community-patch#5]
When entering the dashboard thru the “Dashboard” button, guilds are not shown. View screenshot.
![D01B8DC6-42E6-417C-A92E-B14A292E8B30](https://user-images.githubusercontent.com/98553181/226439539-80715f62-c20f-48e0-99ab-5d528a3eea51.jpeg)

**Comment by Dalkskkskk** [comment]
is your bot in any servers?

**Comment by ghost** [comment]
> is your bot in any servers?

Yes it is, servers are also whitelisted. Dw it’s not that

**Comment by ghost** [comment]
the issue is probably when it checks for the server to give the user all perms

**Comment by Dalkskkskk** [comment]
join https://discord.gg/FWEMy39j and go to troubleshooting help channel

**Comment by Dalkskkskk** [comment]
oh wait, i just realised you're banned

**Comment by Dalkskkskk** [comment]
welp, considering most people in the hangar don't want to help you for what you did, tuff luck. and I'm not even that much of a developer anyways.

**Comment by metal0** [comment]
Can't replicate
